---
title: "Abstract submission for EGPROC 2020 is open!"
date: 2020-02-25
---

<p>We are happy to announce the call for papers for the European Group of Process Tracing Studies (EGPROC) Annual Meeting. The deadline for submissions of abstracts is March 13, 2020.<br>EGPROC will take place at Tilburg University from June 17 to June 19, 2020. Please find the call for papers and the submission form on our website: <a class="" href="https://www.tilburguniversity.edu/research/institutes-and-research-groups/tiber/egproc-2020">https://www.tilburguniversity.edu/research/institutes-and-research-groups/tiber/egproc-2020</a><br>EGPROC brings together researchers from different disciplines such as behavioral economists, as well as cognitive, economic and social psychologists with a shared interest in process tracing in judgment and decision making. The 2020 EGPROC meeting consists of a one-day symposium and a two-day workshop. In the symposium, we aim to invite speakers to discuss merits and challenges of different process tracing tools, and the future potential lying in their integration. In the subsequent workshop, current work relating to human decision makers introduced by researchers from diverse backgrounds and career levels will be discussed.<br>We look forward to your submissions and hope to see you in Tilburg in June!<br>Best,<br>Rima-Maria Rahal, Christoph Kogler &amp; Marcel Zeelenberg</p>
