---
title: "EGPROC 2022 in Amsterdam"
date: 2022-04-15
---

<p><em>Dear colleagues,</em></p>

<p><em>the abstract submission deadline for the European Group of Process Tracing Studies (EGPROC) Annual Meeting has been extended to<strong>April 19th</strong>. Please use this link to submit your contribution:&nbsp;<a href="https://forms.gle/FKReHCd433Ribk2v9" target="_blank" rel="noreferrer noopener">https://forms.gle/FKReHCd433Ribk2v9</a></em></p>

<p><em>We will host EGPROC 2022 on June 29-30, and a post-conference workshop on July 1 on-site at the University of Amsterdam, Roeterseiland Campus.&nbsp;</em></p>

<p><em>You can find more information at&nbsp;<a href="https://neuroeconomist.net/egproc" target="_blank" rel="noreferrer noopener">https://neuroeconomist.net/egproc</a>, and can submit your contribution also directly there.<br></em></p>

<p><strong><em>Mariska Kret&nbsp;</em></strong><em>(University of Leiden) and&nbsp;<strong>Joanna Lahey</strong>&nbsp;(Texas A&amp;M) will give keynote lectures for the EGPROC conference. The workshop will end with a lecture by&nbsp;<strong>Vojtěch Bartoš</strong>&nbsp;(LMU Munich).</em></p>

<p><em>We look forward to your submissions and hope to see you in Amsterdam this summer!</em></p>

<p><em>All the best,</em></p>

<p><em>Jan Hausfeld, Dianna Amasino, Alejandro Hirmas, Jan Engelmann, Carsten de Dreu</em></p>
