"""Generates the Quarto site's migrated content: reads the extracted
WordPress JSON, classifies each item via content_map, rewrites its
content, and writes one .qmd per kept item plus CONTENT_AUDIT.md.

One-time migration script -- not part of the served site.
"""

import json
from pathlib import Path

from content_map import (
    APPEND, BODY_OVERRIDES, DROP_IDS, MEETINGS_PAGE_ID, TEXT_FIXES, resolve_target,
)
from media import copy_and_get_url
from rewrite import (
    parse_meetings, render_meetings_table, rewrite_attachment_links,
    rewrite_internal_links, rewrite_wp_uploads_links, strip_gutenberg,
    unwrap_safelinks,
)

REPO_ROOT = Path(__file__).parent.parent
EXTRACTED = Path(__file__).parent / "_extracted"
UPLOADS_ROOT = Path(
    "/Users/michael/git_stuff/wp_egproc/egproc-org-20260922-113210-8q9p1q94pb7l/uploads"
)
IMAGES_OUT = REPO_ROOT / "images"
FILES_OUT = REPO_ROOT / "files"


def load(name):
    return json.loads((EXTRACTED / name).read_text())


def yaml_quote(value):
    return value.replace("\\", "\\\\").replace('"', '\\"')


def build_frontmatter(item, section):
    lines = ["---", f'title: "{yaml_quote(item["title"])}"']
    if item["type"] == "post":
        lines.append(f"date: {item['date'][:10]}")
    lines.append("---")
    return "\n".join(lines)


def build_slug_to_path(items):
    result = {}
    for item in items:
        target = resolve_target(item)
        if target is not None:
            result[item["slug"]] = f"{target[0]}/{target[1]}"
    return result


def transform_content(item, ctx):
    """Apply the full rewrite pipeline to one item's stored content.
    ctx keys: uploads_root, images_out, files_out, attachment_files,
    slug_to_path."""
    id_ = item["id"]
    if id_ in BODY_OVERRIDES:
        content = BODY_OVERRIDES[id_]
    else:
        content = strip_gutenberg(item["content"])
        content = unwrap_safelinks(content)
        content = rewrite_attachment_links(
            content, ctx["attachment_files"], ctx["uploads_root"],
            ctx["images_out"], ctx["files_out"])
        content = rewrite_wp_uploads_links(
            content, ctx["uploads_root"], ctx["images_out"], ctx["files_out"])
        content = rewrite_internal_links(content, ctx["slug_to_path"])
        for old, new in TEXT_FIXES.get(id_, []):
            if old not in content:
                raise ValueError(f"text fix for id {id_} did not match: {old!r}")
            content = content.replace(old, new)
    if id_ == MEETINGS_PAGE_ID:
        intro = "\n".join(l for l in content.splitlines() if not l[:4].isdigit()).strip()
        content = intro + "\n\n" + render_meetings_table(parse_meetings(content))
    if id_ in APPEND:
        content = content.rstrip() + "\n\n" + APPEND[id_]
    return content.strip()


def vendor_all_pdfs(attachment_files):
    copied = unresolved = 0
    for rel_path in attachment_files.values():
        if not rel_path.lower().endswith(".pdf"):
            continue
        if copy_and_get_url(rel_path, UPLOADS_ROOT, IMAGES_OUT, FILES_OUT) is None:
            unresolved += 1
        else:
            copied += 1
    return copied, unresolved


def write_content_audit(dropped, written):
    lines = [
        "# Content Audit",
        "",
        "Generated by `tools/transform.py` — do not hand-edit. Lists every",
        "published WordPress page/post that was dropped during migration and",
        "why, every text fix applied, and where each migrated item landed.",
        "",
        "## Dropped items",
        "",
    ]
    for item in sorted(dropped, key=lambda i: i["id"]):
        lines.append(f"- **{item['title']}** (WP id {item['id']}, slug `{item['slug']}`): "
                     f"{DROP_IDS[item['id']]}")
    lines += ["", "## Content fixes", ""]
    for id_, fixes in sorted(TEXT_FIXES.items()):
        for old, new in fixes:
            lines.append(f"- WP id {id_}: `{old}` → `{new}`")
    for id_ in sorted(BODY_OVERRIDES):
        lines.append(f"- WP id {id_}: body replaced by a plain-text version "
                     "(pasted email markup removed; wording unchanged).")
    for id_, text in sorted(APPEND.items()):
        lines.append(f"- WP id {id_}: appended: {text}")
    lines.append("- Outlook safelinks wrappers unwrapped; Gutenberg block comments, "
                 "empty paragraphs and `&nbsp;` spacers removed everywhere.")
    lines.append("- Program links on the dead host `eadm.abcde.biz` and on "
                 "`egproc.org/wp-content/uploads/` point at the vendored PDFs in `files/`.")
    lines.append("- History page rendered as a table (Year · Place · Organisers · Program).")
    lines += ["", f"## Migrated: {len(written)} items", ""]
    for item, section, filename in sorted(written, key=lambda w: f"{w[1]}/{w[2]}"):
        lines.append(f"- **{item['title']}** (WP id {item['id']}) → {section}/{filename}.qmd")
    (REPO_ROOT / "CONTENT_AUDIT.md").write_text("\n".join(lines) + "\n")


def main():
    items = load("pages.json") + load("posts.json")
    attachment_files = {a["id"]: a["file"] for a in load("attachments.json") if a["file"]}
    ctx = {
        "uploads_root": UPLOADS_ROOT, "images_out": IMAGES_OUT, "files_out": FILES_OUT,
        "attachment_files": attachment_files, "slug_to_path": build_slug_to_path(items),
    }
    written, dropped = [], []
    for item in items:
        target = resolve_target(item)
        if target is None:
            dropped.append(item)
            continue
        section, filename = target
        out_dir = REPO_ROOT / section
        out_dir.mkdir(parents=True, exist_ok=True)
        body = transform_content(item, ctx)
        (out_dir / f"{filename}.qmd").write_text(
            f"{build_frontmatter(item, section)}\n\n{body}\n")
        written.append((item, section, filename))
    copied, unresolved = vendor_all_pdfs(attachment_files)
    write_content_audit(dropped, written)
    print(f"Wrote {len(written)} .qmd files, dropped {len(dropped)} items.")
    print(f"Vendored {copied} PDFs ({unresolved} unresolved).")


if __name__ == "__main__":
    main()
